---
- name: Criar VLAN no FortiGate
  hosts: fortigate
  connection: httpapi          # Usa a conexão HTTPAPI do Ansible
  gather_facts: no

  vars:
    # Credenciais – pode ser token ou usuário/senha
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no      # mudar para yes em produção
    ansible_user: admin    # opcional, se usar usuário/senha
    ansible_password: admin "# opcional
    # ou, se usar token:
    # ansible_httpapi_token: "{{ vault_fgt_token }}"

    # Dados da VLAN que será criada
    vlan_id: 100
    vlan_name: "VLAN_100"
    interface_physical: "port5"   # interface física onde a VLAN será anexada
    ip_address: "192.168.100.1/24"
    dhcp_server_enable: true

  tasks:

    - name: Garantir que a interface VLAN não exista ainda
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          name: "{{ vlan_name }}"
          type: "vlan"
          vlanid: "{{ vlan_id }}"
          interface: "{{ interface_physical }}"
          ip: "{{ ip_address }}"
          allowaccess: "ping https ssh"
          dhcp_relay_service: "disable"
          status: "up"
      register: result_vlan

    - name: Exibir resultado da criação da VLAN
      debug:
        msg: "VLAN criada/atualizada: {{ result_vlan }}"

    - name: (Opcional) Configurar DHCP Server para a VLAN
      when: dhcp_server_enable
      fortinet.fortios.fortios_system_dhcp_server:
        vdom: "root"
        state: "present"
        system_dhcp_server:
          name: "dhcp_{{ vlan_name }}"
          interface: "{{ vlan_name }}"
          lease_time: 86400
          default_gateway: "{{ ip_address.split('/')[0] }}"
          netmask: "255.255.255.0"
          dns_server1: "8.8.8.8"
          dns_server2: "8.8.4.4"
          ip_range:
            - start_ip: "192.168.100.10"
              end_ip: "192.168.100.200"
      register: result_dhcp

    - name: Mostrar status do DHCP
      debug:
        msg: "DHCP configurado: {{ result_dhcp }}"