---
- name: Hostname Config
  hosts: routers

  tasks:

  - name: Apply the provided configuration
    cisco.ios.ios_hostname:
      config:
        hostname: ROUTER_1_PRINCIPAL
      state: merged





